apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go-2
  namespace: default
  labels:                 # Add labels to match with a Delivery
    app: my-test-4
spec:
  template:
    spec:
      containers:
        - image: nginx
          env:
            - name: TARGET
              value: "Go Sample v1"
